jobs:
  compress:
    runs-on: ubuntu-24.04

    steps:
      - name: Download pmos artifact
        uses: actions/download-artifact@v4
        with:
          name: pmos-samsung-j4primelte-phosh-run4

      - name: Check extracted files
        run: |
          ls -lah
          find . -maxdepth 2 -type f -o -type l

      - name: Create tar xz archive
        run: |
          tar -cJf pmos-samsung-j4primelte-phosh.tar.xz .

      - name: Upload compressed artifact
        uses: actions/upload-artifact@v4
        with:
          name: pmos-samsung-j4primelte-phosh-compressed
          path: pmos-samsung-j4primelte-phosh.tar.xz
